### ISSUE TITLE
Update SensorML API Wiki page

### ISSUE THREAD

**Issue by mikebotts** [sensiasoft/sensorhub#26]
The SensorML API Wiki page needs annexation or updating to reflect ability to use the SWE Common helper class for simpler and more compact assignment of property values.

**Comment by sensiasoft** [comment]
Tutorial and underlying test source code was fixed to make use of SMLHelper and SWEHelper classes. The wiki paged was moved to the new documentation site on [This Page](sensiasoft.github.io/sensorhub/docs/2015-04-16-sensorml-api.html)
